name: Continuous deployment
on:
  push:
    branches:
    - uat

jobs:
  build-admin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Build and Push Worker Docker Image
      run: |-
        docker build -t test:01 .
